spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CLEARDB_DATABASE_URL}
    username: ${CLEARDB_DATABASE_USER}
    password: ${CLEARDB_DATABASE_PASSWORD}

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto=update:

server:
  error:
    include-message: always
  port: ${PORT:8080}